DROP TABLE IF EXISTS tel;
DROP TABLE IF EXISTS ligne_facture;
DROP TABLE IF EXISTS facture;
DROP TABLE IF EXISTS logement;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS emetteur;
DROP TABLE IF EXISTS adresse;
